#############################################################################
# Makefile for building: bin/COP290
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Apr 5 22:00:13 2018
# Project:  COP290.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile COP290.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iinclude/qtgui -Iinclude/graphics -Iinclude/glm -I/usr/X11R6/include -Igenerated_files
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lGLU -lglut -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/qtgui/mainwindow.cpp \
		src/qtgui/dialog3dinput.cpp \
		src/qtgui/object3dfunctionswindow.cpp \
		src/qtgui/translatedialogt.cpp \
		src/qtgui/scaledialog.cpp \
		src/qtgui/rotatedialog.cpp \
		src/qtgui/reflectdialog.cpp \
		src/qtgui/projectiondialog.cpp \
		src/qtgui/dialogorthoinput.cpp \
		src/qtgui/orthofunctionsdialog.cpp \
		src/graphics/display.cpp \
		src/graphics/object2D.cpp \
		src/graphics/object3D.cpp \
		src/graphics/orthographic.cpp \
		src/graphics/point.cpp generated_files/moc_mainwindow.cpp \
		generated_files/moc_dialog3dinput.cpp \
		generated_files/moc_object3dfunctionswindow.cpp \
		generated_files/moc_translatedialogt.cpp \
		generated_files/moc_scaledialog.cpp \
		generated_files/moc_rotatedialog.cpp \
		generated_files/moc_reflectdialog.cpp \
		generated_files/moc_projectiondialog.cpp \
		generated_files/moc_dialogorthoinput.cpp \
		generated_files/moc_orthofunctionsdialog.cpp
OBJECTS       = build/main.o \
		build/mainwindow.o \
		build/dialog3dinput.o \
		build/object3dfunctionswindow.o \
		build/translatedialogt.o \
		build/scaledialog.o \
		build/rotatedialog.o \
		build/reflectdialog.o \
		build/projectiondialog.o \
		build/dialogorthoinput.o \
		build/orthofunctionsdialog.o \
		build/display.o \
		build/object2D.o \
		build/object3D.o \
		build/orthographic.o \
		build/point.o \
		build/moc_mainwindow.o \
		build/moc_dialog3dinput.o \
		build/moc_object3dfunctionswindow.o \
		build/moc_translatedialogt.o \
		build/moc_scaledialog.o \
		build/moc_rotatedialog.o \
		build/moc_reflectdialog.o \
		build/moc_projectiondialog.o \
		build/moc_dialogorthoinput.o \
		build/moc_orthofunctionsdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		COP290.pro
QMAKE_TARGET  = COP290
DESTDIR       = bin/
TARGET        = bin/COP290

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: COP290.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile COP290.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile COP290.pro

dist: 
	@$(CHK_DIR_EXISTS) build/COP2901.0.0 || $(MKDIR) build/COP2901.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/COP2901.0.0/ && $(COPY_FILE) --parents include/qtgui/mainwindow.h include/qtgui/dialog3dinput.h include/qtgui/object3dfunctionswindow.h include/qtgui/translatedialogt.h include/qtgui/scaledialog.h include/qtgui/rotatedialog.h include/qtgui/reflectdialog.h include/qtgui/projectiondialog.h include/qtgui/dialogorthoinput.h include/qtgui/orthofunctionsdialog.h include/graphics/display.h include/graphics/object2D.h include/graphics/object3D.h include/graphics/orthographic.h include/graphics/point.h build/COP2901.0.0/ && $(COPY_FILE) --parents src/main.cpp src/qtgui/mainwindow.cpp src/qtgui/dialog3dinput.cpp src/qtgui/object3dfunctionswindow.cpp src/qtgui/translatedialogt.cpp src/qtgui/scaledialog.cpp src/qtgui/rotatedialog.cpp src/qtgui/reflectdialog.cpp src/qtgui/projectiondialog.cpp src/qtgui/dialogorthoinput.cpp src/qtgui/orthofunctionsdialog.cpp src/graphics/display.cpp src/graphics/object2D.cpp src/graphics/object3D.cpp src/graphics/orthographic.cpp src/graphics/point.cpp build/COP2901.0.0/ && (cd `dirname build/COP2901.0.0` && $(TAR) COP2901.0.0.tar COP2901.0.0 && $(COMPRESS) COP2901.0.0.tar) && $(MOVE) `dirname build/COP2901.0.0`/COP2901.0.0.tar.gz . && $(DEL_FILE) -r build/COP2901.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: generated_files/moc_mainwindow.cpp generated_files/moc_dialog3dinput.cpp generated_files/moc_object3dfunctionswindow.cpp generated_files/moc_translatedialogt.cpp generated_files/moc_scaledialog.cpp generated_files/moc_rotatedialog.cpp generated_files/moc_reflectdialog.cpp generated_files/moc_projectiondialog.cpp generated_files/moc_dialogorthoinput.cpp generated_files/moc_orthofunctionsdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated_files/moc_mainwindow.cpp generated_files/moc_dialog3dinput.cpp generated_files/moc_object3dfunctionswindow.cpp generated_files/moc_translatedialogt.cpp generated_files/moc_scaledialog.cpp generated_files/moc_rotatedialog.cpp generated_files/moc_reflectdialog.cpp generated_files/moc_projectiondialog.cpp generated_files/moc_dialogorthoinput.cpp generated_files/moc_orthofunctionsdialog.cpp
generated_files/moc_mainwindow.cpp: include/qtgui/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/mainwindow.h -o generated_files/moc_mainwindow.cpp

generated_files/moc_dialog3dinput.cpp: include/qtgui/dialog3dinput.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/dialog3dinput.h -o generated_files/moc_dialog3dinput.cpp

generated_files/moc_object3dfunctionswindow.cpp: include/qtgui/object3dfunctionswindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/object3dfunctionswindow.h -o generated_files/moc_object3dfunctionswindow.cpp

generated_files/moc_translatedialogt.cpp: include/qtgui/translatedialogt.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/translatedialogt.h -o generated_files/moc_translatedialogt.cpp

generated_files/moc_scaledialog.cpp: include/qtgui/scaledialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/scaledialog.h -o generated_files/moc_scaledialog.cpp

generated_files/moc_rotatedialog.cpp: include/qtgui/rotatedialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/rotatedialog.h -o generated_files/moc_rotatedialog.cpp

generated_files/moc_reflectdialog.cpp: include/qtgui/reflectdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/reflectdialog.h -o generated_files/moc_reflectdialog.cpp

generated_files/moc_projectiondialog.cpp: include/qtgui/projectiondialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/projectiondialog.h -o generated_files/moc_projectiondialog.cpp

generated_files/moc_dialogorthoinput.cpp: include/qtgui/dialogorthoinput.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/dialogorthoinput.h -o generated_files/moc_dialogorthoinput.cpp

generated_files/moc_orthofunctionsdialog.cpp: include/qtgui/orthofunctionsdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/qtgui/orthofunctionsdialog.h -o generated_files/moc_orthofunctionsdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/mainwindow.o: src/qtgui/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o src/qtgui/mainwindow.cpp

build/dialog3dinput.o: src/qtgui/dialog3dinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dialog3dinput.o src/qtgui/dialog3dinput.cpp

build/object3dfunctionswindow.o: src/qtgui/object3dfunctionswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/object3dfunctionswindow.o src/qtgui/object3dfunctionswindow.cpp

build/translatedialogt.o: src/qtgui/translatedialogt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/translatedialogt.o src/qtgui/translatedialogt.cpp

build/scaledialog.o: src/qtgui/scaledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scaledialog.o src/qtgui/scaledialog.cpp

build/rotatedialog.o: src/qtgui/rotatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/rotatedialog.o src/qtgui/rotatedialog.cpp

build/reflectdialog.o: src/qtgui/reflectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/reflectdialog.o src/qtgui/reflectdialog.cpp

build/projectiondialog.o: src/qtgui/projectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/projectiondialog.o src/qtgui/projectiondialog.cpp

build/dialogorthoinput.o: src/qtgui/dialogorthoinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dialogorthoinput.o src/qtgui/dialogorthoinput.cpp

build/orthofunctionsdialog.o: src/qtgui/orthofunctionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/orthofunctionsdialog.o src/qtgui/orthofunctionsdialog.cpp

build/display.o: src/graphics/display.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/display.o src/graphics/display.cpp

build/object2D.o: src/graphics/object2D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/object2D.o src/graphics/object2D.cpp

build/object3D.o: src/graphics/object3D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/object3D.o src/graphics/object3D.cpp

build/orthographic.o: src/graphics/orthographic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/orthographic.o src/graphics/orthographic.cpp

build/point.o: src/graphics/point.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/point.o src/graphics/point.cpp

build/moc_mainwindow.o: generated_files/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o generated_files/moc_mainwindow.cpp

build/moc_dialog3dinput.o: generated_files/moc_dialog3dinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dialog3dinput.o generated_files/moc_dialog3dinput.cpp

build/moc_object3dfunctionswindow.o: generated_files/moc_object3dfunctionswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_object3dfunctionswindow.o generated_files/moc_object3dfunctionswindow.cpp

build/moc_translatedialogt.o: generated_files/moc_translatedialogt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_translatedialogt.o generated_files/moc_translatedialogt.cpp

build/moc_scaledialog.o: generated_files/moc_scaledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_scaledialog.o generated_files/moc_scaledialog.cpp

build/moc_rotatedialog.o: generated_files/moc_rotatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_rotatedialog.o generated_files/moc_rotatedialog.cpp

build/moc_reflectdialog.o: generated_files/moc_reflectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_reflectdialog.o generated_files/moc_reflectdialog.cpp

build/moc_projectiondialog.o: generated_files/moc_projectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_projectiondialog.o generated_files/moc_projectiondialog.cpp

build/moc_dialogorthoinput.o: generated_files/moc_dialogorthoinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dialogorthoinput.o generated_files/moc_dialogorthoinput.cpp

build/moc_orthofunctionsdialog.o: generated_files/moc_orthofunctionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_orthofunctionsdialog.o generated_files/moc_orthofunctionsdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

